[package]
name = "Pulse"
version = "1.0.0"
authors = []

[addresses]
Pulse = "0x78a349ed835712bb5056761595110896ccf3497de4ef8af46acf8cc719b32e8e"

[dev-addresses]
Pulse = "0xCAFE"

[dependencies]
# Compatible revision with Movement testnet
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-release-v1.8" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "aptos-release-v1.8" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "aptos-release-v1.8" }
